Try to detect bad data from Morningstar

diff --git a/cron b/cron
--- a/cron
+++ b/cron
@@ -17,50 +17,60 @@ dummy_stocks=(
   CLBK
 )
 
-declare -A actions=(
-  [default]=1
-  [check-dummy-stocks]=1
-)
-
+prog="$0"
 usage() {
-  printf 'usage: %s [default | check-dummy-stocks]\n' "$0" >&2
+  printf 'usage: %s [-h] [--headless] [ticker_symbol ...]\n' "$prog" >&2
 }
+funds=()
+while (( $# )); do
+  case $1 in
+    -h|--help)
+      usage
+      exit
+      ;;
+    --)
+      shift
+      break
+      ;;
+    -?*)
+      usage
+      printf '%s: error: unknown option %s\n' "$prog" "$1" >&2
+      exit 1
+      ;;
+    *)
+      funds+=("$1")
+      ;;
+  esac
+  shift
+done
+options=()
+while (( $# )); do
+  case $1 in
+    --)
+      shift
+      funds+=("$@")
+      break
+      ;;
+    -?*)
+      options+=("$1")
+      ;;
+    *)
+      funds+=("$1")
+      ;;
+  esac
+  shift
+done
 
-if (( $# < 1 )); then
-  action=default
+args=()
+args+=("${options[@]}")
+args+=(--)
+args+=("${dummy_stocks[@]}")
+if (( ${#funds[@]} < 1 )); then
+  args+=(/dev/null)
 else
-  if (( $# > 1 )); then
-    usage
-    exit 1
-  fi
-  if ! (( ${actions[$1]} )); then
-    usage
-    exit 1
-  fi
-  action="$1"
+  args+=(funds/"$(date +%Y%m%d)-funds.csv")
 fi
-
-case $action in
-  default)
-    csv=funds/"$(date +%Y%m%d)-funds.csv"
-    funds=(
-      FLCOX
-      FXAIX
-      FSPGX
-      FSMDX
-      FSSNX
-      VTSAX
-    )
-    ;;
-  check-dummy-stocks)
-    csv=/dev/null
-    funds=()
-    ;;
-  *)
-    printf '%s: unexpected action %s\n' "$0" "$action" >&2
-    exit 1
-    ;;
-esac
-
+args+=("${funds[@]}")
+echo "${args[@]}"
 source env/bin/activate
-python3 morningstar.py --headless "${dummy_stocks[@]}" "$csv" "${funds[@]}"
+python3 morningstar.py "${args[@]}"
